spring:
  application:
    name: book-api
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres?currentSchema=book_service}
    username: ${USER_DB:book_service}
    password: ${PASSWORD_DB:book_service}
    driver-class-name: org.postgresql.Driver
  liquibase:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres?currentSchema=book_service}
    user: ${USER_DB:book_service}
    password: ${PASSWORD_DB:book_service}
    change-log: classpath:db/changelog/db.changelog-master.yaml
    driver-class-name: org.postgresql.Driver
    liquibase-schema: book_service
    enabled: true
server:
  port: 8081
